---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install curl
  package:
    name: curl
    state: present

- name: Install terraform
  pip:
    name: terraform
    state: present
